### ISSUE TITLE
"crandash" example application does not load properly

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/shiny-examples#57]
URL for the app:

https://gallery.shinyapps.io/087-crandash/

Error in the browser console:

```
Uncaught TypeError: Cannot read property 'render' of null
    at exports.OutputBinding.shinyBinding.renderValue (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/htmlwidgets-0.8/htmlwidgets.js:517:32)
    at exports.OutputBinding.onValueChange (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/shared/shiny.min.js:4:450)
    at exports.OutputBinding.delegator.(anonymous function) [as onValueChange] (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/htmlwidgets-0.8/htmlwidgets.js:112:23)
    at OutputBindingAdapter.onValueChange (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/shared/shiny.min.js:4:20029)
    at ShinyApp.receiveOutput (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/shared/shiny.min.js:3:20097)
    at ShinyApp.<anonymous> (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/shared/shiny.min.js:3:22029)
    at ShinyApp._sendMessagesToHandlers (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/shared/shiny.min.js:3:21834)
    at ShinyApp.dispatchMessage (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/shared/shiny.min.js:3:21624)
    at MultiplexClientChannel.c.onmessage (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/shared/shiny.min.js:3:17488)
    at MultiplexClient.onConnMessage (https://gallery.shinyapps.io/087-crandash/_w_25ddc61a/__assets__/rstudio-connect.js:564:15)
```

**Comment by wch** [comment]
The app loads for me, although I do also see that in my console. I'm using Chrome 55.0.2883.95 on Mac.

**Comment by fereshtehRS** [comment]
It doesn't load on Chrome, but works fine on Firefox and Safari.
Same version of Chrome on Mac:
Version 55.0.2883.95 (64-bit)

May be my Chrome is in a bad state. I'll try again after restart.

**Comment by yihui** [comment]
I can see the problem as well. Same browser and OS as @fereshtehRS:

![image](https://cloud.githubusercontent.com/assets/163582/21825793/bdf10578-d74a-11e6-816b-bf21d1e692f5.png)

**Comment by bborgesr** [comment]
I think we're all seeing the same thing, which is a seemingly completely functional app, but errors on the console as well (same version of Chrome and same OS):

<img width="1424" alt="screen shot 2017-01-11 at 12 44 57 am" src="https://cloud.githubusercontent.com/assets/6527540/21837110/98bb7534-d797-11e6-9bc8-237c84211378.png">

So, it seems like these errors don't actually affect this particular app. Or at least, not in a way that is easily recognizable for us... Or am I misreading this and there is actually a recognizable bug you found, @fereshtehRS?

So, if the app is actually working fine, that's good, but we should probably investigate that anyway and at least get rid of the error-producing code if it's not serving any meaningful purpose...

**Comment by mine-cetinkaya-rundel** [comment]
This issue still seems to persist. One guess is that the errors about the circle attribute have to do with how the circles are being drawn using the `bubbles` package.
